runtime: python27
api_version: 1
threadsafe: true


env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql://root:dwwFFi5nnmttG5n5@/test?unix_socket=/cloudsql/memflash-167204:us-central1:memflash

beta_settings:
    cloud_sql_instances: memflash-167204:us-central1:memflash

handlers:
- url: .*
  script: main.app
  secure: always

libraries:
- name: pycrypto
  version: "2.6.1"
- name: ssl
  version: latest
- name: MySQLdb
  version: "latest"
- name: PIL
  version: "latest"


