runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: basic_user_app.app

libraries:
- name: pycrypto
  version: "2.6.1"
#- name: mysqldb
#  version: "1.2.5"


# Link to mysqldb info for gcloud
#https://cloud.google.com/appengine/docs/standard/python/cloud-sql/  

#mysql temp password and stuff
#2017-04-05T02:58:18.535120Z 1 [Note] A temporary password is generated for root@localhost: w00Ricoyny;g

#root@localhost: w00Ricoyny;g
#If you lose this password, please consult the section How to Reset the Root Password in the MySQL reference manual.